alchemy-fr/Phraseanet-Docs

- fr/Devel/API/Changelog.rst
- fr/Devel/API/V1/Route/Embed/Substitute.rst
- fr/Devel/API/V1/Route/Records/Add.rst
- fr/Devel/API/V1/Route/Records/Embed.rst
- fr/Devel/API/V1/Route/Search.rst
- fr/Devel/API/V1/Routes.rst
nouvelle route embed/substitute
corrections diverses
> route embed/substitute

- fr/FAQ/Medias/Tache-d-archivage.rst
Minor change for pr/update 3.8 on docs.phraseanet.com. Seems outdated.
> Minor change for pr/update 3.8 on docs.phraseanet.com

- en/Devel/API/Changelog.rst
- fr/Devel/API/Changelog.rst
- fr/Devel/API/V1/Route/Embed/Substitute.rst
Cosmetic changes in API Changelog & Route/Embed/Substitute pages.
> Cosmetic changes in API Changelog & Route/Embed/Substitute pages.

- en/Devel/API/V1/Route/Embed/Substitute.rst
- en/Devel/API/V1/Route/Stories/Add.rst
- en/Devel/API/V1/Route/Stories/AddRecords.rst
- en/Devel/API/V1/Route/Stories/SetCover.rst
- en/Devel/API/V1/Routes.rst
- fr/Devel/API/V1/Route/Feeds/Aggregated.rst
- fr/Devel/API/V1/Route/Stories/Add.rst
- fr/Devel/API/V1/Route/Stories/AddRecords.rst
- fr/Devel/API/V1/Route/Stories/Embed.rst
- fr/Devel/API/V1/Route/Stories/SetCover.rst
- fr/Devel/API/V1/Route/Stories/Story.rst
- fr/Devel/API/V1/Routes.rst
add : route Embed/Substitute
fix: fr/en
> add : doc to Stories/ routes : Add, AddRecords, SetCover

- en/Devel/API/V1/Route/Records/Search.rst
- en/Devel/API/V1/Route/Search.rst
- fr/Devel/API/V1/Route/Records/Search.rst
- fr/Devel/API/V1/Route/Search.rst
API Search, Record/Search fix for API Manual 3.8 - Closing PHRAS-518
> API Search, Record/Search fix for API Manual 3.8 - Closing PHRAS-518

- en/Devel/API/V1/Route/Stories/AddRecords.rst
- en/Devel/API/V1/Route/Stories/DelRecords.rst
- en/Devel/API/V1/Routes.rst
- fr/Devel/API/V1/Route/Stories/AddRecords.rst
- fr/Devel/API/V1/Route/Stories/DelRecords.rst
- fr/Devel/API/V1/Routes.rst
add : doc to "stories" routes : DelRecords,
fix: some en/fr errors
> Routes "stories" 3.8

- en/Admin/Prerequisite.rst
- fr/Admin/Prerequis.rst
Updating minimum PHP version for Phraseanet 3.8.
> Work 3.8 : Updating minimum PHP version for Phraseanet 3.8.

- en/Devel/API/V1/Route/Embed/Substitute.rst
- fr/Devel/API/V1/Route/Embed/Substitute.rst
Add note about the optional Adapt parameter in Route/Embed/Substitute
> Add note about the optional Adapt parameter in Route/Embed/Substitute

- en/User/Guide/Actions.rst
- fr/User/Manuel/Actions.rst
Add sharing options considerations for subviews'permalinks in Tools.
> Add sharing options considerations for subviews permalinks in Tools

- en/User/Guide/Actions.rst
- fr/User/Manuel/Actions.rst
Minor change for permalinks sharing due to enhancement from dev desk : it adds Document class documents and subviews in 3.8.8.
> Minor change for permalinks sharing due to enhancement from dev desk

- en/Admin/Console.rst
- en/Devel/API/V1/Route/Records/Add.rst
- fr/Admin/Console.rst
- fr/Devel/API/V1/Route/Records/Add.rst
- Devel/API/Route/Records/Add : observance about the lost of the nosubdefs attribute if document goes in quarantine
- Updating available commands for bin/console & bin/setup
> Minor changes for API Records/Add, Updating commands for bin/console & bin/setup 

- en/Devel/API/V2/Route/Baskets/AddElement.rst
- en/Devel/API/V2/Route/Baskets/RemoveElement.rst
- en/Devel/API/V2/Route/Orders/Create.rst
- en/Devel/API/V2/Routes.rst
- Documentation for basket add element route
- Documentation for basket remove element route
> PHRAS-1070 Add documentation for new basket API routes

- fr/Devel/API/V2/Route/Search.rst
Need to be re-read by Dev Team
> Translation for V2/Route/Search - Mistakes & Deprecated purposes 

- en/Admin/Install.rst
- fr/Admin/Installation.rst
Madatory Post-Installation checks for Searchengine setting AND Subview task setting
> Requiered Post-Installation settings 

- en/Admin/Install.rst
- fr/Admin/Installation.rst
Post-Installation considerations for Searchengine setting AND Subview task setting in FR & EN Admin guides
> Requiered Post-Installation settings configuration

- en/Devel/API/V1/Route/Quarantine/Item.rst
- en/Devel/API/V1/Route/Quarantine/List.rst
- fr/Devel/API/V1/Route/Quarantine/Item.rst
- fr/Devel/API/V1/Route/Quarantine/List.rst
Add record_id in quarantine response
> PHRAS-569 update response quarantine

- en/Devel/API/V1/Route/Quarantine/Item.rst
- en/Devel/API/V1/Route/Quarantine/List.rst
- en/Devel/API/V1/Route/Records/Add.rst
- fr/Devel/API/V1/Route/Quarantine/Item.rst
- fr/Devel/API/V1/Route/Quarantine/List.rst
- fr/Devel/API/V1/Route/Records/Add.rst
- Fix PHRAS-1678 for Records/Add in FR & EN Devel manual
>  Fix PHRAS-1678 for Records/Add in FR & EN Devel manual

- en/Devel/API/V1/Route/Quarantine/Item.rst
- en/Devel/API/V1/Route/Quarantine/List.rst
- en/Devel/API/V2/Route/Quarantine/AddItem.rst
- en/Devel/API/V2/Route/Quarantine/Delete.rst
- en/Devel/API/V2/Route/Quarantine/DeleteItem.rst
- en/Devel/API/V2/Routes.rst
- fr/Devel/API/V1/Route/Quarantine/Item.rst
- fr/Devel/API/V1/Route/Quarantine/List.rst
- fr/Devel/API/V2/Route/Quarantine/AddItem.rst
- fr/Devel/API/V2/Route/Quarantine/Delete.rst
- fr/Devel/API/V2/Route/Quarantine/DeleteItem.rst
- fr/Devel/API/V2/Routes.rst
- Add en and fr V2 quarantine manual
- Update manual V1 quarantine's response sample of phraseanet 4.1
> PHRASA-1679 add en and fr quarantine devel manual

- en/Devel/API/V1/Route/Records/Add.rst
- fr/Devel/API/V1/Route/Records/Add.rst
PHRAS-2487 - Adding Phraseanet 4.0.8 feature Add by URL within API route records/add
> PHRAS-2487 - Adding Phraseanet 4.0.8 feature Add by URL in API

- en/Devel/API/V1/Route/Records/SetMetadatas.rst
- en/Devel/API/V1/Route/Records/SetStatus.rst
- fr/Devel/API/V1/Route/Records/SetMetadatas.rst
- fr/Devel/API/V1/Route/Records/SetStatus.rst
SetMetadatas, SetStatus apply both for document or story (and it seems to be said)
> SetMetadatas, SetStatus apply both for document or story 

- en/Admin/Configuration.rst
- fr/Admin/Configuration.rst
Updating Configuration for Chaptering (PHRAS-1634) and Geolocation (PHRAS-1633)
> Updating for Chaptering (PHRAS-1634) and Geolocation (PHRAS-1633)

- en/Admin/InstallDocker.rst
- fr/Admin/GestionnaireDeWorker.rst
- fr/Admin/InstallationDocker.rst
- Introduce Actions in FR GestionnaireDeWorker as starting point B4 translation
- Update DockerInstall in FR & EN
> PHRAS-3503 : Update DockerInstall in FR & EN, Introduce Actions in FR GestionnaireDeWorker as starting point

- _templates/phraseanet/static/phraseanet.css_t
- bundle_createEnvVariableDoc/src/Blocks/BlockHelper.php
- bundle_createEnvVariableDoc/src/EnvFileParser.php
- bundle_createEnvVariableDoc/src/HtmlGenerator.php
- PHRAS-3575: Simple/double quote italic style, variable followed by equal symbol bold style.
- PHRAS-3575: Flags install/build color.
> PHRAS-3575: Update flags color

- bundle_createEnvVariableDoc/src/Blocks/BlockHelper.php
- PHRAS-3576: Link generation env var fix
> PHRAS-3576: Links generation env var fix

- en/FAQ/Media/Elasticseach-supported-operators.rst
- fr/FAQ/Medias/Recherches-Elasticsearch-dans-phraseanet.rst
- PHRAS-3610: Search record or story where a field have no value, is unset
> PHRAS-3610: Search record or story where a field have no value, is unset
